# Partir de la imagen oficial de node
FROM node:latest

# Variables requeridas
# $repoApi = Repositorio que contiene el código de la api a desplegar
# $apiName = Nombre del proyecto o api

# Variables de entorno en el dockerfile
ENV TZ Europe/Madrid

# Establecer la zona horaria
RUN ln -snf /usr/share/zoneinfo/${TZ} /etc/localtime && echo ${TZ} > /etc/timezone

# Copiar script de construcción a la imagen
COPY setup /root/setup

# Exponer el puerto del servicio de la api
EXPOSE 3000

# Ejecución del script de construcción
CMD [ "bash", "/root/setup/start.sh" ] 

