# Se utiliza ubuntu jammy
FROM ubuntu:jammy

# Variables del dockerfile
ENV TZ Europe/Madrid
ENV DEBIAN_FRONTEND noninteractive

# Establecer la zona horaria
RUN ln -snf /usr/share/zoneinfo/${TZ} /etc/localtime && echo ${TZ} > /etc/timezone

# Se actualiza la lista de paquetes y se instala los paquetes necesarios
RUN apt update -yq && apt install -yq ldap-utils debconf-utils

# Copiar archivos de configuración del demonio slapd
COPY ./setup /root/scripts

# Mantener el contenedor en ejecución
CMD [ "tail", "-f", "/dev/null" ]
