# Se utiliza la imagen de ubuntu "jammy"
FROM ubuntu:jammy

# Variables de entorno en el dockerfile
# Preinstalación
ENV TZ Europe/Madrid
ENV DEBIAN_FRONTEND noninteractive
# Setup DNS
ENV dir_zonas /etc/bind/zones
ENV forwarders '8.8.8.8 8.8.4.4'
ENV domain test.local
ENV ipv4_container 192.168.0.2
ENV ipv4_anfitrion 192.168.1.57

# Establecer la zona horaria
RUN ln -snf /usr/share/zoneinfo/${TZ} /etc/localtime && echo ${TZ} > /etc/timezone

# Actualizar la lista de paquetes e instalar el paquete DNS
RUN apt update -yq && apt install -yq bind9

# Exponer los puertos que utiliza el servicio
EXPOSE 53
EXPOSE 53/udp

# Copiar el script de configuración del servicio DNS en el directorio /root
COPY ./config.sh /root/

# Ejecución del script de configuración
RUN bash /root/config.sh

# Mantener el contenedor en ejecución
CMD [ "service", "named", "start" ]
