# El script que monta el servicio se ejecuta manualmente
# Se utiliza la imagen del servicio ldap de openldap
FROM lfvalcar/openldap

# Variables del dockerfile
ENV DIR_SETUP /root/setup

# Copiar los certificados para SSL/TLS
COPY ./certificate/* ${DIR_SETUP}/

# Exponer el puerto para el servicio
EXPOSE 636

# Mantener el contenedor en ejecución
CMD [ "tail", "-f", "/dev/null" ]
