# Partir de la imagen oficial de node
FROM node:latest

# Instalación de paquetes necesarios para el desarrollo y monitorización remota
RUN apt update && apt install -yq htop openssh-server

# Copiar los archivos de configuración
COPY ./setup /root/setup

# Iniciar script de configuración
RUN bash /root/setup/setup.sh

# Mantener contenedor en ejeución
CMD [ "tail", "-f", "/dev/null" ]