# El script que monta el servicio se ejecuta manualmente
# Partir de la imagen oficial de node
FROM node:latest

# Variables requeridas en la ejecución del contenedor
# ${id_rsa} - El archivo que contiene la clave rsa
# $repo - Repositorio del proyecto que utiliza node y npm como gestor de paquetes

# Instalación de paquetes necesarios para el desarrollo y monitorización remota
RUN apt update && apt install -yq htop openssh-server

# Copiar los archivos de configuración
COPY ./setup /root/setup

# Iniciar script de configuración
RUN bash /root/setup/setup-ssh.sh

# Exponer puertos que se usarán
EXPOSE 22
EXPOSE 3000

# Mantener contenedor en ejeución
CMD [ "bash", "/root/setup/start.sh" ]